### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by vvenla** [tulir/lindeb#19]
Projektia tarkasteltu 3.1. klo 11:30.

Mielenkiintoinen erilainen toteutustapa. Dokumentti on kattava. Luokkakaavio ja relaatiokaavio ovat selkeitä, ja tarvittava monesta moneen -suhde löytyy. Olisin kaivannut ReadMehen helposti löydettävät  testikäyttäjätunnukset, sekä toisen viikon palautuksissa kysytyt linkit sovelluksen näkymiin. Nyt pääsin testaamaan sovellusta vain rekisteröitymällä, ja sen jälkeen itse lisäämällä uusia linkkejä tyhjään pohjaan. Näkymät, joissa olisi valmiiksi sisältöä, auttaisivat hahmottamaan sovelluksen toimintaa paremmin.

Koodi näyttää noudattavan Clean code -periaatteita, toki sen seuraaminen on haastavaa jos ei tunne Gota ym.

**Comment by tulir** [comment]
> Olisin kaivannut ReadMehen helposti löydettävät testikäyttäjätunnukset

Harkitsin asiaa aiemmin, mutta rekisteröityminen on vielä tässä vaiheessa niin helppoa (ei vaadi sähköpostia yms), että päätin jättää testitunnukset pois. Jos lisään sähköpostivaatimuksen (#24) niin lisään varmaan myös demotilan, joka ei vaadi kirjautumista (#22)


> sekä toisen viikon palautuksissa kysytyt linkit sovelluksen näkymiin

Lisäsin linkit sovelluksen näkymiin (commit 819184ae095e14fb07615c474ad37548b5423f94). Erillisiä näkymiä on tosin vain neljä. Lisäksi kirjautuneet käyttäjät eivät pääse kirjautumisnäkymään ja kirjautumattomat käyttäjät pääsevät vain kirjautumisnäkymään.

En tehnyt erikseen staattisia HTML-sivuja, koska niitä ei olisi voinut uudelleenkäyttää helposti näkymien varsinaisissa toteutuksissa.


> Näkymät, joissa olisi valmiiksi sisältöä, auttaisivat hahmottamaan sovelluksen toimintaa paremmin.

Hyvä pointti, taidan lisätä uusille käyttäjille muutaman valmiin linkin ja tagin (#20).
